---
- name: Get device facts and configuration
  hosts: ios
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve device facts and configuration and save facts to file
      juniper_junos_facts:        
        savedir: "{{ playbook_dir }}"
        config_format: "xml"
      register: result

    - name: Print configuration
      debug:
        var: result.ansible_facts.junos.config