---
- name: Manage network devices
  hosts: routers
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 100
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output

- name: Switch specific config
  hosts: switchs
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: Create VLANs
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - vlan 200
          - vlan 300
          - vlan 400
          - vlan 500

      register: print_output

    -  debug: var=print_output
