
- name: Create Network Configuration on a Palo Alto Networks Firewall
  hosts: 107.1.1.254
  connection:  local
  gather_facts:  False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Load Variables
    include_vars: vars.yml

  - name: Push Interface Settings to the Firewall
    changed_when: false
    panos_interface:
      provider: '{{ provider }}'
      if_name: '{{ item.name }}'
      ip: ['{{ item.ip }}']
      zone_name: '{{ item.zone }}'
      mode: '{{ item.mode }}'
      enable_dhcp: no
      commit: no
    with_items: '{{ interfaces }}'
