---
- name: Configure basic firewall policies
  hosts: mysrx
  connection: local
  gather_facts: no
  vars:
    # junos_user: "root"
    # junos_password: "Juniper"
    build_dir: "/tmp/"
    address_entries: [ {'name':'LocalNet','prefix':'172.16.0.0/24'},{'name':'PrivateNet','prefix':'192.168.10.0/24'},{'name':'PublicNet','prefix':'10.10.0.0/22'} ]
    fw_policy_info: [ {'policy_name':'Allow_Policy','src_zone':'trust','dst_zone':'untrust','src_ips':['LocalNet'],'dst_ips':['any'],'action':'permit','apps':['any']}]

  tasks:
    - name: Build address book entries
      ansible.builtin.template:
        src: templates/fw_address_book_global.set.j2
        dest: '{{build_dir}}/fw_address_book_global.set'
      with_items: address_entries

    - name: Apply address book entries
      junipernetworks.junos.junos_config:
        src: '{{ build_dir }}/fw_address_book_global.set'
        backup: yes
        backup_options:
          filename: address-book-backup.cfg

    - name: Build firewall policies config template
      ansible.builtin.template:
        src: 'templates/fw_policy.set.j2'
        dest: '{{build_dir}}/fw_policy.set'
      with_items: fw_policy_info

    - name: Apply firewall policies
      junipernetworks.junos.junos_config:
        src: '{{ build_dir }}/fw_policy.set'
        backup: yes
        backup_options:
          filename: firewall-policy-backup.cfg
