---
- name: Deploy Reggie Registration Portal
  hosts: public_server
  connection: local
  gather_facts: no
  vars:
    reggie_repo_url:   "https://github.com/JNPRAutomate/reggie.git"
    reggie_zip:   "reggie.zip"
    reggie_app_root:   "/reggie"
    reggie_user:  "vagrant"
    reggie_group:   "vagrant"

  tasks:
    - name: Install Python APT
      sudo: yes
      shell: sudo apt-get install python-apt -y

    - name: Install NGINX
      sudo: yes
      apt: name=nginx state=latest update_cache=yes

    - name: Install PIP
      sudo: yes
      apt: name=python-pip state=latest update_cache=no

    - name: creates reggie root directory
      sudo: yes
      file:
        path="{{ reggie_app_root }}"
        state=directory
        owner="{{ reggie_user }}"
        group="{{ reggie_group }}"
        mode=0775

    - name: Download reggie repo (GitHub)
      git:
        repo="{{ reggie_repo_url }}"
        dest="{{ reggie_app_root }}"

    - name: Configure System Python for Reggie
      copy: src=files/.python-version dest={{ reggie_app_root }} owner=vagrant group=vagrant

    - name: install reggie pip requirements
      sudo: yes
      pip: requirements="{{ reggie_app_root }}/requirements.txt" chdir={{ reggie_app_root }} executable=/usr/bin/pip

    - name: Create vSRX License Root Directory
      sudo: yes
      file:
        path=/vsrx_license
        state=directory
        owner=www-data
        group=www-data
        mode=0775

    - name: Create vSRX License Directory
      sudo: yes
      file:
        path=/vsrx_license/license
        state=directory
        owner=www-data
        group=www-data
        mode=0775

    - name: Copy NGINX Config
      sudo: yes
      copy: src=files/reggie_default dest=/etc/nginx/sites-enabled owner=root group=root

    - name: Remove NGINX Default Config
      sudo: yes
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Install Reggie as Upstart service
      sudo: yes
      copy: src=files/reggie.conf dest=/etc/init/reggie.conf owner=root group=root

    - name: Start Reggie service
      sudo: yes
      service: name=reggie state=started

    - name: Restart NGINX service
      sudo: yes
      service: name=nginx state=restarted sleep=5
